-- SQLite

-- CONSULTANDO FUNCIONARIOS E SEUS CARGOS

SELECT E.ID AS 'CÓDIGO',
        E.NAME AS 'NOME',
        P.DESCRIPTION AS 'CARGO'
    FROM EMPLOYEES AS E
    INNER JOIN POSITIONS AS P ON (E.POSITION_ID = P.ID);