-- SQLite

-- CONSULTANDO CLIENTES COM 2 OU MAIS LOCACOES

SELECT C.NAME AS 'NOME CLIENTE',
    COUNT(L.CUSTOMER_ID) AS 'NÚMERO LOCAÇÕES'
     FROM LOCATIONS AS L
    INNER JOIN CUSTOMERS AS C ON (C.ID = L.CUSTOMER_ID)
    GROUP BY L.CUSTOMER_ID
    HAVING COUNT(L.CUSTOMER_ID) >= 2;
