-- SQLite

-- CONSULTANDO LOCACOES COM NOME CLIENTE, AUTOMOVEL E FUNCIONARIO

SELECT C.NAME AS 'NOME CLIENTE',
    CA.NAME AS 'NOME AUTOMÓVEL',
    E.NAME AS 'NOME FUNCIONÁRIO'
    FROM LOCATIONS AS L
    INNER JOIN CUSTOMERS AS C ON (L.CUSTOMER_ID = C.ID)
    INNER JOIN CARS AS CA ON (L.CAR_ID = CA.ID)
    INNER JOIN EMPLOYEES AS E ON (L.EMPLOYEE_ID = E.ID);